import React, { Component } from 'react'
import { connect } from 'react-redux'
import { Button, Form, Input } from 'antd'
import Spacer from 'components/CleanUIComponents/Spacer'
import { validateOtp } from 'redux/user/actions'
import styles from '../style.module.scss'

const mapStateToProps = ({ user }) => ({
  loading: user.loading,
  // isCustomerLoading: general.isCustomerLoading,
  emailId: user.email,
  mfaToken: user.mfaToken,
})

@Form.create()
@connect(mapStateToProps)
class ValidateCode extends Component {
  onSubmit = event => {
    event.preventDefault()
    const { form, dispatch, mfaToken, emailId } = this.props
    form.validateFields((error, values) => {
      if (!error) {
        values.mfa_token = mfaToken
        values.email = emailId
        dispatch(validateOtp(values))
      }
    })
  }

  render() {
    const { form, loading } = this.props
    const headerLine =
      'Please enter the 6 digit code generated by your OTP Authentication app. As a reminder, you might have set this up using an app such as "Google Authenticator" or "Authy"'
    return (
      <div>
        <div className={styles.block}>
          <div className="row">
            <div className="col-xl-12">
              <div className={styles.inner}>
                <div className={styles.form}>
                  <div className={styles.lockIcon}>
                    <img src="resources/images/lock.png" alt="Authentication" width="50%" />
                    <Spacer height="20px" />
                    <h5 className={styles.header}>Two-Factor Authentication</h5>
                    <p>{headerLine}</p>
                    {/* <p>Download an authenticator app, like Google Authenticator then enter your code</p> */}
                  </div>
                  <Spacer height="20px" />
                  <Form layout="vertical" onSubmit={this.onSubmit}>
                    <Form.Item>
                      {form.getFieldDecorator('code', {
                        initialValue: '',
                        rules: [
                          {
                            required: true,
                            min: 6,
                            max: 6,
                            message: 'Please input your 6-digit code',
                          },
                        ],
                      })(
                        <Input
                          type="password"
                          style={{
                            textAlign: 'center',
                            padding: '16px',
                            fontSize: '12px',
                            letterSpacing: '6px',
                          }}
                          placeholder="6-digit code"
                        />,
                      )}
                    </Form.Item>
                    <Spacer height="40px" />
                    <div className={styles.btnBlock}>
                      <Button
                        block
                        className="width-200 mr-2"
                        type="primary"
                        htmlType="submit"
                        loading={loading}
                      >
                        Sign In Securely
                      </Button>
                    </div>
                  </Form>
                  <Spacer height="22px" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

export default ValidateCode
