const actions = {
  UPLOAD_VENDOR_BALANCE_STATEMENTS: 'UPLOAD_VENDOR_BALANCE_STATEMENTS',
  UPLOAD_VENDOR_BALANCE_STATEMENTS_SUCCESS: 'UPLOAD_VENDOR_BALANCE_STATEMENTS_SUCCESS',
  UPLOAD_VENDOR_BALANCE_STATEMENTS_FAILURE: 'UPLOAD_VENDOR_BALANCE_STATEMENTS_FAILURE',

  UPLOAD_VENDOR_TRANSACTIONS_STATEMENTS: 'UPLOAD_VENDOR_TRANSACTIONS_STATEMENTS',
  UPLOAD_VENDOR_TRANSACTIONS_STATEMENTS_SUCCESS: 'UPLOAD_VENDOR_TRANSACTIONS_STATEMENTS_SUCCESS',
  UPLOAD_VENDOR_TRANSACTIONS_STATEMENTS_FAILURE: 'UPLOAD_VENDOR_TRANSACTIONS_STATEMENTS_FAILURE',

  GET_ALL_VENDOR_STATEMENTS: 'GET_ALL_VENDOR_STATEMENTS',
  GET_ALL_VENDOR_STATEMENTS_SUCCESS: 'GET_ALL_VENDOR_STATEMENTS_SUCCESS',
  GET_ALL_VENDOR_STATEMENTS_FAILURE: 'GET_ALL_VENDOR_STATEMENTS_FAILURE',

  GET_VENDOR_STATEMENTS_BY_FILTERS: 'GET_VENDOR_STATEMENTS_BY_FILTERS',
  GET_VENDOR_STATEMENTS_BY_FILTERS_SUCCESS: 'GET_VENDOR_STATEMENTS_BY_FILTERS_SUCCESS',
  GET_VENDOR_STATEMENTS_BY_FILTERS_FAILURE: 'GET_VENDOR_STATEMENTS_BY_FILTERS_FAILURE',

  GET_VENDOR_STATEMENTS_BY_FILENAME: 'GET_VENDOR_STATEMENTS_BY_FILENAME',
  GET_VENDOR_STATEMENTS_BY_FILENAME_SUCCESS: 'GET_VENDOR_STATEMENTS_BY_FILENAME_SUCCESS',
  GET_VENDOR_STATEMENTS_BY_FILENAME_FAILURE: 'GET_VENDOR_STATEMENTS_BY_FILENAME_FAILURE',

  UPDATE_ERROR_LIST_DATA: 'UPDATE_ERROR_LIST_DATA',
}
export default actions

export const uploadBalanceStatements = (value, token) => {
  return {
    type: actions.UPLOAD_VENDOR_BALANCE_STATEMENTS,
    value,
    token,
  }
}

export const uploadTransactionStatements = (value, token) => {
  return {
    type: actions.UPLOAD_VENDOR_TRANSACTIONS_STATEMENTS,
    value,
    token,
  }
}

export const getAllVendorStatements = token => {
  return {
    type: actions.GET_ALL_VENDOR_STATEMENTS,
    token,
  }
}

export const getVendorStatementsByfilters = (value, token) => {
  return {
    type: actions.GET_VENDOR_STATEMENTS_BY_FILTERS,
    value,
    token,
  }
}

export const getVendorStatementsByFilename = (filename, token) => {
  return {
    type: actions.GET_VENDOR_STATEMENTS_BY_FILENAME,
    filename,
    token,
  }
}

export const updateErrorList = value => {
  return {
    type: actions.UPDATE_ERROR_LIST_DATA,
    value,
  }
}
