const actions = {
  GET_CRYPTO_BENEFICIARIES: 'GET_CRYPTO_BENEFICIARIES',
  GET_CRYPTO_BENEFICIARIES_SUCCESS: 'GET_CRYPTO_BENEFICIARIES_SUCCESS',
  GET_CRYPTO_BENEFICIARIES_FAILURE: 'GET_CRYPTO_BENEFICIARIES_FAILURE',

  GET_CRYPTO_BENEFICIARY_BY_ID: 'GET_CRYPTO_BENEFICIARY_BY_ID',
  GET_CRYPTO_BENEFICIARY_BY_ID_SUCCESS: 'GET_CRYPTO_BENEFICIARY_BY_ID_SUCCESS',
  GET_CRYPTO_BENEFICIARY_BY_ID_FALIURE: 'GET_CRYPTO_BENEFICIARY_BY_ID_FALIURE',

  CREATE_CRYPTO_BENEFICIARY: 'CREATE_CRYPTO_BENEFICIARY',
  CREATE_CRYPTO_BENEFICIARY_SUCCESS: 'CREATE_CRYPTO_BENEFICIARY_SUCCESS',
  CREATE_CRYPTO_BENEFICIARY_FAILURE: 'CREATE_CRYPTO_BENEFICIARY_FAILURE',

  UPDATE_SELECTED_CRYPTO_BENEFICIARY: 'UPDATE_SELECTED_CRYPTO_BENEFICIARY',
  // UPDATE_SELECTED_BENEFICIARY_SUCCESS: 'UPDATE_SELECTED_CRYPTO_BENEFICIARY_SUCCESS',
  // UPDATE_SELECTED_CRYPTO_BENEFICIARY_FAILURE: 'UPDATE_SELECTED_CRYPTO_BENEFICIARY_FAILURE',

  UPDATE_CRYPTO_BENEFICIARY: 'UPDATE_CRYPTO_BENEFICIARY',
  UPDATE_CRYPTO_BENEFICIARY_SUCCESS: 'UPDATE_CRYPTO_BENEFICIARY_SUCCESS',
  UPDATE_CRYPTO_BENEFICIARY_FAILURE: 'UPDATE_CRYPTO_BENEFICIARY_FAILURE',

  UDPATE_CRYPTO_BENE_STATUS: 'UDPATE_CRYPTO_BENE_STATUS',
  UDPATE_CRYPTO_BENE_STATUS_SUCCESS: 'UDPATE_CRYPTO_BENE_STATUS_SUCCESS',
  UDPATE_CRYPTO_BENE_STATUS_FAILURE: 'UDPATE_CRYPTO_BENE_STATUS_FAILURE',

  DELETE_CRYPTO_BENEFICIARY: 'DELETE_CRYPTO_BENEFICIARY',
  DELETE_CRYPTO_BENEFICIARY_SUCCESS: 'DELETE_CRYPTO_BENEFICIARY_SUCCESS',
  DELETE_CRYPTO_BENEFICIARY_FAILURE: 'DELETE_CRYPTO_BENEFICIARY_FAILURE',

  GET_FORMATED_CRYPTO_BENEFICIARY: 'GET_FORMATED_CRYPTO_BENEFICIARY',

  HANDLE_CRYPTO_BENEFICIARIES_PAGINATION: 'HANDLE_CRYPTO_BENEFICIARIES_PAGINATION',

  GET_BULK_DOWNLOAD_FOR_CRYPTO_BENEFICIARY: 'GET_BULK_DOWNLOAD_FOR_CRYPTO_BENEFICIARY',
  GET_BULK_DOWNLOAD_FOR_CRYPTO_BENEFICIARY_SUCCESS:
    'GET_BULK_DOWNLOAD_FOR_CRYPTO_BENEFICIARY_SUCCESS',
  GET_BULK_DOWNLOAD_FOR_CRYPTO_BENEFICIARY_FAILURE:
    'GET_BULK_DOWNLOAD_FOR_CRYPTO_BENEFICIARY_FAILURE',

  HANDLE_CRYPTO_BENEFICIARY_FILTERS: 'HANDLE_CRYPTO_BENEFICIARY_FILTERS',
}

export default actions

export const updateBeneficiaryStatus = (value, token) => {
  return {
    type: actions.UDPATE_CRYPTO_BENE_STATUS,
    value,
    token,
  }
}

export const handleCryptoBeneficiaryFilters = value => {
  return {
    type: actions.HANDLE_CRYPTO_BENEFICIARY_FILTERS,
    value,
  }
}

export const getBulkDownloadDataForCryptoBeneficiary = value => {
  return {
    type: actions.GET_BULK_DOWNLOAD_FOR_CRYPTO_BENEFICIARY,
    value,
  }
}

export const getCryptoBeneficiaries = (value, token) => {
  return {
    type: actions.GET_CRYPTO_BENEFICIARIES,
    value,
    token,
  }
}

export const getCryptoBeneficiaryById = (id, token) => {
  return {
    type: actions.GET_CRYPTO_BENEFICIARY_BY_ID,
    id,
    token,
  }
}

export const getFormatedCryptoBeneficiary = value => {
  return {
    type: actions.GET_FORMATED_CRYPTO_BENEFICIARY,
    value,
  }
}

export const createCryptoBeneficiary = (value, token) => {
  return {
    type: actions.CREATE_CRYPTO_BENEFICIARY,
    value,
    token,
  }
}

export const updateSelectedCryptoBeneficiary = value => {
  return {
    type: actions.UPDATE_SELECTED_CRYPTO_BENEFICIARY,
    value,
  }
}

export const updateCryptoBeneficiary = (value, token) => {
  return {
    type: actions.UPDATE_CRYPTO_BENEFICIARY,
    value,
    token,
  }
}

export const deleteCryptoBeneficiary = (value, token) => {
  return {
    type: actions.DELETE_CRYPTO_BENEFICIARY,
    value,
    token,
  }
}

export const handlePagination = (value, token) => {
  return {
    type: actions.HANDLE_CRYPTO_BENEFICIARIES_PAGINATION,
    value,
    token,
  }
}
