const actions = {
  GET_CLIENT_MANAGEMENT: 'GET_CLIENT_MANAGEMENT',
  GET_CLIENT_MANAGEMENT_SUCCESS: 'GET_CLIENT_MANAGEMENT_SUCCESS',
  GET_CLIENT_MANAGEMENT_FAILURE: 'GET_CLIENT_MANAGEMENT_FAILURE',

  GET_CLIENT_MANAGEMENT_BY_ID: 'GET_CLIENT_MANAGEMENT_BY_ID',
  GET_CLIENT_MANAGEMENT_BY_ID_SUCCESS: 'GET_CLIENT_MANAGEMENT_BY_ID_SUCCESS',
  GET_CLIENT_MANAGEMENT_BY_ID_FALIURE: 'GET_CLIENT_MANAGEMENT_BY_ID_FALIURE',

  UPDATE_CLIENT_MANAGEMENT: 'UPDATE_CLIENT_MANAGEMENT',
  UPDATE_CLIENT_MANAGEMENT_SUCCESS: 'UPDATE_CLIENT_MANAGEMENT_SUCCESS',
  UPDATE_CLIENT_MANAGEMENT_FALIURE: 'UPDATE_CLIENT_MANAGEMENT_FALIURE',

  HANDLE_CLIENT_MANAGEMENT_PAGINATION: 'HANDLE_CLIENT_MANAGEMENT_PAGINATION',

  GET_PAYCONSTRUCT_PRODUCTS: 'GET_PAYCONSTRUCT_PRODUCTS',
  GET_PAYCONSTRUCT_PRODUCTS_SUCCESS: 'GET_PAYCONSTRUCT_PRODUCTS_SUCCESS',
  GET_PAYCONSTRUCT_PRODUCTS_FAILURE: 'GET_PAYCONSTRUCT_PRODUCTS_FAILURE',

  GET_DOCUMENTS_FILE: 'GET_DOCUMENTS_FILE',
  GET_DOCUMENTS_FILE_SUCCESS: 'GET_DOCUMENTS_FILE_SUCCESS',
  GET_DOCUMENTS_FILE_FAILURE: 'GET_DOCUMENTS_FILE_FAILURE',

  REMOVE_DOCUMENT_FILES: 'REMOVE_DOCUMENT_FILES',
  REMOVE_DOCUMENT_FILES_SUCCESS: 'REMOVE_DOCUMENT_FILES_SUCCESS',
  REMOVE_DOCUMENT_FILES_FAILURE: 'REMOVE_DOCUMENT_FILES_FAILURE',

  GET_ALL_STAKEHOLDERS_BY_ID: 'GET_ALL_STAKEHOLDERS_BY_ID',
  GET_ALL_STAKEHOLDERS_BY_ID_SUCCESS: 'GET_ALL_STAKEHOLDERS_BY_ID_SUCCESS',
  GET_ALL_STAKEHOLDERS_BY_ID_FAILURE: 'GET_ALL_STAKEHOLDERS_BY_ID_FAILURE',

  GET_PRESIGNED_URL: 'GET_PRESIGNED_URL',
  GET_PRESIGNED_URL_SUCCESS: 'GET_PRESIGNED_URL_SUCCESS',
  GET_PRESIGNED_URL_FAILURE: 'GET_PRESIGNED_URL_FAILURE',

  GET_PRESIGNED_URL_PREVIEW: 'GET_PRESIGNED_URL_PREVIEW',
  GET_PRESIGNED_URL_PREVIEW_SUCCESS: 'GET_PRESIGNED_URL_PREVIEW_SUCCESS',
  GET_PRESIGNED_URL_PREVIEW_FAILURE: 'GET_PRESIGNED_URL_PREVIEW_FAILURE',

  GET_PRESIGNED_URL_DOWNLOAD: 'GET_PRESIGNED_URL_DOWNLOAD',
  GET_PRESIGNED_URL_DOWNLOAD_SUCCESS: 'GET_PRESIGNED_URL_DOWNLOAD_SUCCESS',
  GET_PRESIGNED_URL_DOWNLOAD_FAILURE: 'GET_PRESIGNED_URL_DOWNLOAD_FAILURE',

  GET_STAKEHOLDER_PRESIGNED_URL_PREVIEW: 'GET_STAKEHOLDER_PRESIGNED_URL_PREVIEW',
  GET_STAKEHOLDER_PRESIGNED_URL_PREVIEW_SUCCESS: 'GET_STAKEHOLDER_PRESIGNED_URL_PREVIEW_SUCCESS',
  GET_STAKEHOLDER_PRESIGNED_URL_PREVIEW_FAILURE: 'GET_STAKEHOLDER_PRESIGNED_URL_PREVIEW_FAILURE',

  GET_STAKEHOLDER_PRESIGNED_URL_DOWNLOAD: 'GET_STAKEHOLDER_PRESIGNED_URL_DOWNLOAD',
  GET_STAKEHOLDER_PRESIGNED_URL_DOWNLOAD_SUCCESS: 'GET_STAKEHOLDER_PRESIGNED_URL_DOWNLOAD_SUCCESS',
  GET_STAKEHOLDER_PRESIGNED_URL_DOWNLOAD_FAILURE: 'GET_STAKEHOLDER_PRESIGNED_URL_DOWNLOAD_FAILURE',

  UPLOAD_FILE: 'UPLOAD_FILE',
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_FAILURE: 'UPLOAD_FILE_FAILURE',

  GET_DOCUMENTS_QUESTIONS: 'GET_DOCUMENTS_QUESTIONS',
  GET_DOCUMENTS_QUESTIONS_SUCCESS: 'GET_DOCUMENTS_QUESTIONS_SUCCESS',
  GET_DOCUMENTS_QUESTIONS_FAILURE: 'GET_DOCUMENTS_QUESTIONS_FAILURE',

  UPDATE_DOCUMENT_STATUS: 'UPDATE_DOCUMENT_STATUS',
  UPDATE_DOCUMENT_STATUS_SUCCESS: 'UPDATE_DOCUMENT_STATUS_SUCCESS',
  UPDATE_DOCUMENT_STATUS_FAILURE: 'UPDATE_DOCUMENT_STATUS_FAILURE',

  UPDATE_SELECTED_INDUSTRY_INFORMATION: 'UPDATE_SELECTED_INDUSTRY_INFORMATION',

  UPDATE_OVERALL_APPLICATION_STATUS: 'UPDATE_OVERALL_APPLICATION_STATUS',
  UPDATE_OVERALL_APPLICATION_STATUS_SUCCESS: 'UPDATE_OVERALL_APPLICATION_STATUS_SUCCESS',
  UPDATE_OVERALL_APPLICATION_STATUS_FAILURE: 'UPDATE_OVERALL_APPLICATION_STATUS_FAILURE',

  UPDATE_KYC_REFRESH_DATE: 'UPDATE_KYC_REFRESH_DATE',
  UPDATE_KYC_REFRESH_DATE_SUCCESS: 'UPDATE_KYC_REFRESH_DATE_SUCCESS',
  UPDATE_KYC_REFRESH_DATE_FAILURE: 'UPDATE_KYC_REFRESH_DATE_FAILURE',

  SEND_COMPLIANCE_REVIEW_MAIL: 'SEND_COMPLIANCE_REVIEW_MAIL',
  SEND_COMPLIANCE_REVIEW_MAIL_SUCCESS: 'SEND_COMPLIANCE_REVIEW_MAIL_SUCCESS',
  SEND_COMPLIANCE_REVIEW_MAIL_FAILURE: 'SEND_COMPLIANCE_REVIEW_MAIL_FAILURE',
}
export default actions

export const updateKycRefreshDate = (value, token) => {
  return {
    type: actions.UPDATE_KYC_REFRESH_DATE,
    value,
    token,
  }
}

export const getAllClientManagement = (value, token) => {
  return {
    type: actions.GET_CLIENT_MANAGEMENT,
    value,
    token,
  }
}

export const getClientManagementById = (id, token) => {
  return {
    type: actions.GET_CLIENT_MANAGEMENT_BY_ID,
    id,
    token,
  }
}

export const updateClientManagement = (id, value, token) => {
  return {
    type: actions.UPDATE_CLIENT_MANAGEMENT,
    id,
    value,
    token,
  }
}

export const handlePagination = (value, token) => {
  return {
    type: actions.HANDLE_CLIENT_MANAGEMENT_PAGINATION,
    value,
    token,
  }
}
