import React from 'react'
import { Button, Form, Input } from 'antd'
import { connect } from 'react-redux'
import { withRouter } from 'react-router-dom'
import InfoCard from 'components/customComponents/InfoCard'
import { twoFAauthorizationModal } from 'redux/auth0/actions'

import styles from './style.module.scss'

const mapStateToProps = ({ user }) => ({
  token: user.token,
  role: user.role,
  // loading: permissions.loading,
  // isPermissionAdded: permissions.isPermissionAdded,
})

@Form.create()
@withRouter
@connect(mapStateToProps)
class AuthorizationModal extends React.Component {
  handleCancel = () => {
    const { dispatch } = this.props
    dispatch(twoFAauthorizationModal(false))
  }

  // onSubmit = event => {
  //   event.preventDefault()
  //   const { form } = this.props
  //   form.validateFields((error, values) => {
  //     if (!error) {
  //       console.log(values)

  //     }
  //   })
  // }

  render() {
    const { loading, authorizePayment, formProps } = this.props
    const headerLine =
      'Please enter the 6 digit code generated by your OTP Authentication app. As a reminder, you might have set this up using an app such as "Google Authenticator" or "Authy"'
    return (
      <div>
        <div className={styles.modalHeader}>
          <InfoCard
            minHeight="82px"
            imgHeight="100px"
            imgTop="46%"
            header="Two-Factor Authentication"
            closeButton={this.handleCancel}
          />
        </div>
        <Form
          hideRequiredMark={false}
          layout="vertical"
          className={styles.formBlock}
          onSubmit={authorizePayment}
        >
          <div className="row">
            <div className="text-center">
              <img src="resources/images/lock.png" alt="Authentication" width="20%" />
            </div>
            <div className="col-md-12 col-lg-12 text-center mb-5">{headerLine}</div>
            <div className="col-md-12 col-lg-12">
              <Form.Item label="Enter your 6-digit verification code" hasFeedback>
                {formProps.getFieldDecorator('code', {
                  initialValue: '',
                  rules: [
                    {
                      required: true,
                      min: 6,
                      max: 6,
                      message: 'Please input your 6-digit code',
                    },
                  ],
                })(
                  <Input
                    className={styles.inputbox}
                    style={{
                      textAlign: 'center',
                      padding: '18px',
                      fontSize: '12px',
                      letterSpacing: '6px',
                      width: '100%',
                    }}
                    type="password"
                    placeholder="6-digit code"
                  />,
                )}
              </Form.Item>
            </div>
          </div>
          <div className={styles.formActions}>
            <div className="form-actions">
              <Button className={styles.btnConfirm} htmlType="submit" loading={loading}>
                CONFIRM
              </Button>
            </div>
          </div>
        </Form>
      </div>
    )
  }
}

export default AuthorizationModal
